# Generated by Django 5.2.10 on 2026-01-25 23:45

import core.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(validators=[core.models.validate_age])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('class_grade', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=3)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits and start with '07'.", regex='^07[0-9]{8}$')])),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('home_address', models.TextField()),
                ('student_photo', models.ImageField(upload_to='students/photos/')),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Graduated', 'Graduated')], default='Active', max_length=10)),
            ],
        ),
    ]
