# Generated by Django 5.0 on 2026-01-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="salary",
        ),
        migrations.AddField(
            model_name="teacher",
            name="salary_encrypted",
            field=models.TextField(blank=True, null=True),
        ),
    ]
