# Generated by Django 5.0 on 2026-01-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_teacher_salary_teacher_salary_encrypted"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="time_slot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("08:00 - 09:00", "08:00 - 09:00"),
                    ("09:00 - 10:00", "09:00 - 10:00"),
                    ("10:00 - 11:00", "10:00 - 11:00"),
                    ("11:00 - 12:00", "11:00 - 12:00"),
                    ("12:00 - 13:00", "12:00 - 13:00"),
                    ("14:00 - 15:00", "14:00 - 15:00"),
                    ("15:00 - 16:00", "15:00 - 16:00"),
                    ("16:00 - 17:00", "16:00 - 17:00"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together={
                (
                    "course",
                    "class_grade",
                    "term",
                    "academic_year",
                    "day_of_week",
                    "time_slot",
                )
            },
        ),
    ]
