# Generated by Django 5.0 on 2026-01-26 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_created_at_student_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('contact_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits and start with '07'.", regex='^07[0-9]{8}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('qualification', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=20)),
                ('employment_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Part-time', 'Part-time')], max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('teacher_photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 digits and start with '07'.", regex='^07[0-9]{8}$')])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teachers', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_teachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
