# Generated by Django 5.0 on 2026-01-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_course_teacher_subject_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
