from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('students/register/', views.student_registration, name='student_registration'),
    path('students/import/', views.student_bulk_import, name='student_bulk_import'),
    path('students/export/', views.export_students_excel, name='export_students_excel'),
    path('students/', views.student_list, name='student_list'),
    path('students/<int:student_id>/', views.student_profile, name='student_profile'),
    path('students/<int:student_id>/update/', views.student_update, name='student_update'),
    path('students/<int:student_id>/delete/', views.student_delete, name='student_delete'),
    path('teachers/', views.teacher_list, name='teacher_list'),
    path('teachers/register/', views.teacher_registration, name='teacher_registration'),
    path('teachers/<int:teacher_id>/', views.teacher_profile, name='teacher_profile'),
    path('teachers/<int:teacher_id>/timetable/', views.teacher_timetable, name='teacher_timetable'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/create/', views.course_creation, name='course_creation'),
    path('teachers/assign/', views.teacher_assignment, name='teacher_assignment'),
    path('students/enroll/', views.enrollment, name='enrollment'),
    path('students/bulk-enroll/', views.bulk_enrollment, name='bulk_enrollment'),
    path('attendance/', views.attendance, name='attendance'),
    path('attendance/bulk/', views.bulk_attendance, name='bulk_attendance'),
    path('reports/attendance/student/', views.student_attendance_report, name='student_attendance_report'),
    path('reports/attendance/class/', views.class_attendance_report, name='class_attendance_report'),
    path('finance/payments/', views.payment_list, name='payment_list'),
    path('finance/payments/record/', views.record_payment, name='record_payment'),
    path('finance/payments/<int:payment_id>/receipt/', views.generate_receipt, name='generate_receipt'),
    path('grades/record/', views.record_grade, name='record_grade'),
]
